In [29]:
from tensorflow.keras.preprocessing.text import one_hot

In [30]:
### Sentences
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understanding the meaning of words',
        'your videos are good']

In [31]:
## Define the vocabulary size
voc_size = 10000

In [32]:
### One Hot Representation
one_hot_repr=[one_hot(words, voc_size) for words in sent]
one_hot_repr

[[5644, 3063, 6892, 5061],
 [5644, 3063, 6892, 1092],
 [5644, 1966, 6892, 8816],
 [2642, 6091, 8897, 2817, 8908],
 [2642, 6091, 8897, 2817, 5105],
 [8714, 5644, 5766, 6892, 82],
 [8783, 2227, 3535, 2817]]

In [33]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [34]:
import numpy as np

In [35]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5644 3063 6892 5061]
 [   0    0    0    0 5644 3063 6892 1092]
 [   0    0    0    0 5644 1966 6892 8816]
 [   0    0    0 2642 6091 8897 2817 8908]
 [   0    0    0 2642 6091 8897 2817 5105]
 [   0    0    0 8714 5644 5766 6892   82]
 [   0    0    0    0 8783 2227 3535 2817]]


In [36]:
## feature representation
dim=10

In [37]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [38]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step


array([[[ 0.04533619,  0.0268159 ,  0.02471889,  0.00540195,
          0.00535934,  0.02403009,  0.01392553, -0.02606758,
          0.00838047,  0.00149956],
        [ 0.04533619,  0.0268159 ,  0.02471889,  0.00540195,
          0.00535934,  0.02403009,  0.01392553, -0.02606758,
          0.00838047,  0.00149956],
        [ 0.04533619,  0.0268159 ,  0.02471889,  0.00540195,
          0.00535934,  0.02403009,  0.01392553, -0.02606758,
          0.00838047,  0.00149956],
        [ 0.04533619,  0.0268159 ,  0.02471889,  0.00540195,
          0.00535934,  0.02403009,  0.01392553, -0.02606758,
          0.00838047,  0.00149956],
        [-0.02571117,  0.01796127, -0.01225749,  0.04524019,
          0.04039732,  0.03684975,  0.03747154,  0.02230846,
         -0.00442077,  0.0360576 ],
        [-0.01986228, -0.03359004,  0.03969062, -0.0042091 ,
          0.01690623, -0.03828954,  0.03612446, -0.03475048,
         -0.0407529 , -0.01141803],
        [ 0.01540485, -0.02463067,  0.03363036, -0.0